# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/caesar_bc1.txt -o data/latin_library_bert/caesar_bc1.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/caesar_bc2.txt -o data/latin_library_bert/caesar_bc2.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/caesar_bc3.txt -o data/latin_library_bert/caesar_bc3.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/caesar_bellafr.txt -o data/latin_library_bert/caesar_bellafr.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/caesar_gall1.txt -o data/latin_library_bert/caesar_gall1.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/caesar_gall2.txt -o data/latin_library_bert/caesar_gall2.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/caesar_gall3.txt -o data/latin_library_bert/caesar_gall3.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/caesar_gall4.txt -o data/latin_library_bert/caesar_gall4.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/caesar_gall5.txt -o data/latin_library_bert/caesar_gall5.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/caesar_gall6.txt -o data/latin_library_bert/caesar_gall6.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/caesar_gall7.txt -o data/latin_library_bert/caesar_gall7.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/caesar_gall8.txt -o data/latin_library_bert/caesar_gall8.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/vergil_aen1.txt -o data/latin_library_bert/vergil_aen1.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/vergil_aen10.txt -o data/latin_library_bert/vergil_aen10.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/vergil_aen11.txt -o data/latin_library_bert/vergil_aen11.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/vergil_aen12.txt -o data/latin_library_bert/vergil_aen12.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/vergil_aen2.txt -o data/latin_library_bert/vergil_aen2.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/vergil_aen3.txt -o data/latin_library_bert/vergil_aen3.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/vergil_aen4.txt -o data/latin_library_bert/vergil_aen4.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/vergil_aen5.txt -o data/latin_library_bert/vergil_aen5.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/vergil_aen6.txt -o data/latin_library_bert/vergil_aen6.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/vergil_aen7.txt -o data/latin_library_bert/vergil_aen7.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/vergil_aen8.txt -o data/latin_library_bert/vergil_aen8.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/vergil_aen9.txt -o data/latin_library_bert/vergil_aen9.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/vergil_ec1.txt -o data/latin_library_bert/vergil_ec1.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/vergil_ec10.txt -o data/latin_library_bert/vergil_ec10.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/vergil_ec2.txt -o data/latin_library_bert/vergil_ec2.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/vergil_ec3.txt -o data/latin_library_bert/vergil_ec3.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/vergil_ec4.txt -o data/latin_library_bert/vergil_ec4.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/vergil_ec5.txt -o data/latin_library_bert/vergil_ec5.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/vergil_ec6.txt -o data/latin_library_bert/vergil_ec6.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/vergil_ec7.txt -o data/latin_library_bert/vergil_ec7.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/vergil_ec8.txt -o data/latin_library_bert/vergil_ec8.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/vergil_ec9.txt -o data/latin_library_bert/vergil_ec9.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/vergil_geo1.txt -o data/latin_library_bert/vergil_geo1.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/vergil_geo2.txt -o data/latin_library_bert/vergil_geo2.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/vergil_geo3.txt -o data/latin_library_bert/vergil_geo3.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/vergil_geo4.txt -o data/latin_library_bert/vergil_geo4.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/lucan_lucan1.txt -o data/latin_library_bert/lucan_lucan1.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/lucan_lucan10.txt -o data/latin_library_bert/lucan_lucan10.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/lucan_lucan2.txt -o data/latin_library_bert/lucan_lucan2.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/lucan_lucan3.txt -o data/latin_library_bert/lucan_lucan3.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/lucan_lucan4.txt -o data/latin_library_bert/lucan_lucan4.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/lucan_lucan5.txt -o data/latin_library_bert/lucan_lucan5.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/lucan_lucan6.txt -o data/latin_library_bert/lucan_lucan6.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/lucan_lucan7.txt -o data/latin_library_bert/lucan_lucan7.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/lucan_lucan8.txt -o data/latin_library_bert/lucan_lucan8.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/lucan_lucan9.txt -o data/latin_library_bert/lucan_lucan9.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.amor1.txt -o data/latin_library_bert/ovid_ovid.amor1.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.amor2.txt -o data/latin_library_bert/ovid_ovid.amor2.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.amor3.txt -o data/latin_library_bert/ovid_ovid.amor3.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.artis1.txt -o data/latin_library_bert/ovid_ovid.artis1.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.artis2.txt -o data/latin_library_bert/ovid_ovid.artis2.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.artis3.txt -o data/latin_library_bert/ovid_ovid.artis3.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.fasti1.txt -o data/latin_library_bert/ovid_ovid.fasti1.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.fasti2.txt -o data/latin_library_bert/ovid_ovid.fasti2.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.fasti3.txt -o data/latin_library_bert/ovid_ovid.fasti3.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.fasti4.txt -o data/latin_library_bert/ovid_ovid.fasti4.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.fasti5.txt -o data/latin_library_bert/ovid_ovid.fasti5.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.fasti6.txt -o data/latin_library_bert/ovid_ovid.fasti6.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.her1.txt -o data/latin_library_bert/ovid_ovid.her1.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.her10.txt -o data/latin_library_bert/ovid_ovid.her10.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.her11.txt -o data/latin_library_bert/ovid_ovid.her11.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.her12.txt -o data/latin_library_bert/ovid_ovid.her12.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.her13.txt -o data/latin_library_bert/ovid_ovid.her13.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.her14.txt -o data/latin_library_bert/ovid_ovid.her14.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.her15.txt -o data/latin_library_bert/ovid_ovid.her15.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.her16.txt -o data/latin_library_bert/ovid_ovid.her16.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.her17.txt -o data/latin_library_bert/ovid_ovid.her17.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.her18.txt -o data/latin_library_bert/ovid_ovid.her18.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.her19.txt -o data/latin_library_bert/ovid_ovid.her19.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.her2.txt -o data/latin_library_bert/ovid_ovid.her2.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.her20.txt -o data/latin_library_bert/ovid_ovid.her20.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.her21.txt -o data/latin_library_bert/ovid_ovid.her21.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.her3.txt -o data/latin_library_bert/ovid_ovid.her3.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.her4.txt -o data/latin_library_bert/ovid_ovid.her4.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.her5.txt -o data/latin_library_bert/ovid_ovid.her5.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.her6.txt -o data/latin_library_bert/ovid_ovid.her6.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.her7.txt -o data/latin_library_bert/ovid_ovid.her7.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.her8.txt -o data/latin_library_bert/ovid_ovid.her8.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.her9.txt -o data/latin_library_bert/ovid_ovid.her9.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.ibis.txt -o data/latin_library_bert/ovid_ovid.ibis.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.met1.txt -o data/latin_library_bert/ovid_ovid.met1.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.met10.txt -o data/latin_library_bert/ovid_ovid.met10.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.met11.txt -o data/latin_library_bert/ovid_ovid.met11.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.met12.txt -o data/latin_library_bert/ovid_ovid.met12.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.met13.txt -o data/latin_library_bert/ovid_ovid.met13.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.met14.txt -o data/latin_library_bert/ovid_ovid.met14.txt
python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.met15.txt -o data/latin_library_bert/ovid_ovid.met15.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.met2.txt -o data/latin_library_bert/ovid_ovid.met2.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.met3.txt -o data/latin_library_bert/ovid_ovid.met3.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.met4.txt -o data/latin_library_bert/ovid_ovid.met4.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.met5.txt -o data/latin_library_bert/ovid_ovid.met5.txt
# python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.met6.txt -o data/latin_library_bert/ovid_ovid.met6.txt
python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.met7.txt -o data/latin_library_bert/ovid_ovid.met7.txt
python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.met8.txt -o data/latin_library_bert/ovid_ovid.met8.txt
python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.met9.txt -o data/latin_library_bert/ovid_ovid.met9.txt
python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.ponto1.txt -o data/latin_library_bert/ovid_ovid.ponto1.txt
python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.ponto2.txt -o data/latin_library_bert/ovid_ovid.ponto2.txt
python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.ponto3.txt -o data/latin_library_bert/ovid_ovid.ponto3.txt
python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.ponto4.txt -o data/latin_library_bert/ovid_ovid.ponto4.txt
python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.rem.txt -o data/latin_library_bert/ovid_ovid.rem.txt
python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.tristia1.txt -o data/latin_library_bert/ovid_ovid.tristia1.txt
python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.tristia2.txt -o data/latin_library_bert/ovid_ovid.tristia2.txt
python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.tristia3.txt -o data/latin_library_bert/ovid_ovid.tristia3.txt
python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.tristia4.txt -o data/latin_library_bert/ovid_ovid.tristia4.txt
python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/ovid_ovid.tristia5.txt -o data/latin_library_bert/ovid_ovid.tristia5.txt
python3 scripts/gen_berts_to_file.py --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -f data/latin_library_text/catullus.txt -o data/latin_library_bert/catullus.txt
